### ISSUE TITLE
Difference between Re-fungible and Divisible

### ISSUE THREAD

**Issue by okwme** [interNFT/use-cases#3]
What't the difference between "Re-fungible" and "Divisible"? I've always thought of re-fungible as fractional ownership and wasn't sure what "interchangeable units of information" meant exactly.

```
Re-fungible to mint fungible tokens which represent interchangeable units of information.
Divisible to allow fractional ownership of non-fungible parts.
```

**Comment by svabhishek** [comment]
Hi @ig-shaun - based on the document, is it accurate to assume the following:

1) re-fungible => Input NFT and get FTs (fungible tokens) as fractional parts;
2) divisible NFT => Input NFT and get NFTs (non-fungible tokens) as fractional parts

?

**Comment by deepanshutr** [comment]
Both the requirements are synonymous. Propose to merge both into one: 
Fractional Ownership- to allow for multiple fractional owners to a singular NFT

**Comment by okwme** [comment]
"Re-fungible" is a fun name and I'm the author of the EIP but it's actually pretty confusing and the key word that makes the concept understandable is "Fractional". Let's combine the two and use "Fractional"?

**Comment by ig-shaun** [comment]
I agree that the term 'Re-fungible' is confusing - thanks @okwme for conceding that we should use a more literal term.
However, we may need further disambiguation here of what we mean by "fractional" vs. "divisible", to align with concepts in law relating to collective control/ownership of assets and associated rights. 
Fractionally controlled/owned assets (we use the more generic term _Resources_) may be divisible or indivisible.
For instance, a plot of land which is collectively owned is indivisible, but fractional ownership is possible through unitised shares. In contrast, a collection of Château Margaux 1972 vintage wines is divisible and fractional ownership in the collection may include the right to divide the collection by withdrawing units (individual bottles). The bottles in this set are fungible, but the collection is not.
